version: build-{build}
init:
- ps: >-
    echo "Project: $env:APPVEYOR_PROJECT_NAME"

    echo "Tag: $env:APPVEYOR_REPO_TAG_NAME"

    echo "Branch $env:APPVEYOR_REPO_BRANCH"

    echo "Commit $env:APPVEYOR_REPO_COMMIT"


    IF ($env:APPVEYOR_REPO_TAG -eq "true") {

    Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME (build $env:APPVEYOR_BUILD_NUMBER)"

    $env:FILE_VERSION = $env:APPVEYOR_REPO_TAG_NAME.Substring(1)

    $env:PRODUCT_VERSION = $env:APPVEYOR_REPO_TAG_NAME.Substring(1)

    } else {

    $env:FILE_VERSION = $env:APPVEYOR_REPO_COMMIT

    $env:PRODUCT_VERSION = $env:APPVEYOR_REPO_COMMIT

    }
image: Visual Studio 2015
install:
- cmd: cinst autoit.commandline -y -r | find "Extracting" /v | find "shim" /v
build_script:
- ps: >-
    aut2exe /in doublescreen-ebs.au3 /pack /out doublescreen-ebs-x86.exe /fileversion "$env:FILE_VERSION" /productversion "$env:PRODUCT_VERSION"

    aut2exe /in java-alerts-bot.au3 /pack /out java-alerts-bot-x86.exe /fileversion "$env:FILE_VERSION" /productversion "$env:PRODUCT_VERSION"

    aut2exe /in doublescreen-ebs.au3 /pack /out doublescreen-ebs-x64.exe /x64 /fileversion "$env:FILE_VERSION" /productversion "$env:PRODUCT_VERSION"

    aut2exe /in java-alerts-bot.au3 /pack /out java-alerts-bot-x64.exe /x64 /fileversion "$env:FILE_VERSION" /productversion "$env:PRODUCT_VERSION"

    IF ($env:APPVEYOR_REPO_TAG -eq "true") {

      7z a "$env:APPVEYOR_PROJECT_NAME-$env:APPVEYOR_REPO_TAG_NAME-x64.zip" "$env:APPVEYOR_BUILD_FOLDER\*-x64.exe"

      7z a "$env:APPVEYOR_PROJECT_NAME-$env:APPVEYOR_REPO_TAG_NAME-x86.zip" "$env:APPVEYOR_BUILD_FOLDER\*-x86.exe"

    }
artifacts:
- path: '*.exe'
  name: windows-binaries
- path: '*.zip'
  name: windows-packages
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: DHeT+KPQh27VwA8VDS+ps7uvoW+lYs+LW3Z4O3R4dg3CJPipa11h12NEtB3vsUbc
  artifact: windows-binaries,windows-packages
  release: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_TAG_NAME)
  force_update: true
  on:
    appveyor_repo_tag: true
